export let listofFirst = [
  {
    dim: "4",
    id: "identityDocId",
    title: "Identifier Number",
    isMandatory: true,
    placeholder: "Enter Identifier Number",
    val: "1988123456",
    disable: true,
  },
  {
    dim: "4",
    id: "name",
    title: "Full Name",
    isMandatory: true,
    placeholder: "Enter full Name",
    val: "Moin Mostakin",
    disable: true,
  },
  {
    dim: "4",
    id: "dob",
    title: "Date of birth",
    isMandatory: true,
    placeholder: "Enter date of birth",
    val: "1988-09-19",
    disable: true,
  },
  {
    dim: "4",
    id: "nameBn",
    title: "পূর্ণনাম",
    isMandatory: true,
    placeholder: "পূর্ণনাম",
    val: "পূর্ণনাম পূর্ণনাম",
    disable: true,
  },
  {
    dim: "4",
    id: "mobile",
    title: "Mobile Number",
    isMandatory: true,
    placeholder: "Mobile Number",
    val: "01921921987",
    disable: true,
  },
  {
    dim: "4",
    id: "email",
    title: "E-mail",
    isMandatory: false,
    placeholder: "Enter E-mail",
    val: "moin@commlinkinfotech.com",
    disable: true,
  },
];

export let listofSecond = [
  {
    dim: "3",
    id: "f_name",
    title: "Father",
    isMandatory: true,
    placeholder: "Enter Father's Name",
    val: "Aslam Sheik",
    disable: true,
  },
  {
    dim: "3",
    id: "m_name",
    title: "Mother",
    isMandatory: true,
    placeholder: "Enter Mother's Name",
    val: "Rajiya Beghum",
    disable: true,
  },
  {
    dim: "3",
    id: "spouse_name",
    title: "Spouse",
    isMandatory: false,
    placeholder: "Enter Spouse's Name",
    val: "N/A",
    disable: true,
  },
  {
    dim: "3",
    id: "nationality",
    title: "Nationality",
    isMandatory: true,
    val: "Bangladeshi",
    disable: true,
  },
  {
    dim: "3",
    id: "gender",
    title: "Gender",
    isMandatory: true,
    val: "Male",
    disable: true,
  },
  {
    dim: "3",
    id: "marital_status",
    title: "Marital Status",
    isMandatory: true,
    val: "Single",
    disable: true,
  },
];
export let listofThird = [
  {
    dim: "3",
    id: "country",
    title: "Country",
    isMandatory: true,
    val: "Bangladesh",
    disable: true,
  },
  {
    dim: "3",
    id: "division",
    title: "Division",
    isMandatory: true,
    val: "Dhaka",
    disable: true,
  },
  {
    dim: "3",
    id: "district",
    title: "District",
    isMandatory: true,
    val: "Dhaka",
    disable: true,
  },
  {
    dim: "3",
    id: "upozila",
    title: "Upozila",
    isMandatory: true,
    val: "Dhaka",
    disable: true,
  },
  {
    dim: "3",
    id: "cityCorporationOrMunicipality",
    title: "City/Municipality",
    isMandatory: true,
    val: "Dhaka",
    disable: true,
  },
  {
    dim: "3",
    id: "unionOrWard",
    title: "Union/Ward",
    isMandatory: false,
    val: "32 No Ward",
    disable: true,
  },
  {
    dim: "3",
    id: "postOffice",
    title: "Post Office",
    isMandatory: true,
    placeholder: "Enter Post Office",
    val: "Rampura",
    disable: true,
  },
  {
    dim: "3",
    id: "postalCode",
    title: "Postal Code",
    isMandatory: false,
    placeholder: "Enter Postal Code",
    val: "1219",
    disable: true,
  },
  {
    dim: "3",
    id: "additionalMouzaOrMoholla",
    title: "Mouza/Moholla",
    isMandatory: false,
    placeholder: "Enter Mouza/Moholla",
    val: "Moulvirtek Khilgong",
    disable: true,
  },
  {
    dim: "3",
    id: "additionalVillageOrRoad",
    title: "Village/Road",
    isMandatory: true,
    placeholder: "Enter Village/Road",
    val: "Road No 32",
    disable: true,
  },
  {
    dim: "3",
    id: "homeOrHoldingNo",
    title: "House/Holding No",
    isMandatory: true,
    placeholder: "Enter House/Holding No",
    val: "House no 1",
    disable: true,
  },
];
export let listofThirdEdit = [
  {
    dim: "3",
    id: "country",
    title: "Country",
    isMandatory: true,
    val: "Bangladesh",
    disable: true,
  },
  {
    dim: "3",
    id: "division",
    title: "Division",
    isMandatory: true,
    val: "Dhaka",
    disable: false,
  },
  {
    dim: "3",
    id: "district",
    title: "District",
    isMandatory: true,
    val: "Dhaka",
    disable: false,
  },
  {
    dim: "3",
    id: "upozila",
    title: "Upozila",
    isMandatory: true,
    val: "Dhaka",
    disable: false,
  },
  {
    dim: "3",
    id: "cityCorporationOrMunicipality",
    title: "City/Municipality",
    isMandatory: true,
    val: "Dhaka",
    disable: false,
  },
  {
    dim: "3",
    id: "unionOrWard",
    title: "Union/Ward",
    isMandatory: false,
    val: "32 No Ward",
    disable: false,
  },
  {
    dim: "3",
    id: "postOffice",
    title: "Post Office",
    isMandatory: true,
    placeholder: "Enter Post Office",
    val: "Rampura",
    disable: false,
  },
  {
    dim: "3",
    id: "postalCode",
    title: "Postal Code",
    isMandatory: false,
    placeholder: "Enter Postal Code",
    val: "1219",
    disable: false,
  },
  {
    dim: "3",
    id: "additionalMouzaOrMoholla",
    title: "Mouza/Moholla",
    isMandatory: false,
    placeholder: "Enter Mouza/Moholla",
    val: "Moulvirtek Khilgong",
    disable: false,
  },
  {
    dim: "3",
    id: "additionalVillageOrRoad",
    title: "Village/Road",
    isMandatory: true,
    placeholder: "Enter Village/Road",
    val: "Road No 32",
    disable: false,
  },
  {
    dim: "3",
    id: "homeOrHoldingNo",
    title: "House/Holding No",
    isMandatory: true,
    placeholder: "Enter House/Holding No",
    val: "House no 1",
    disable: false,
  },
];
export let listofForth = [
  {
    dim: "3",
    id: "division",
    title: "Division",
    isMandatory: true,
    val: "Dhaka",
    disable: true,
  },
  {
    dim: "3",
    id: "district",
    title: "District",
    isMandatory: true,
    val: "Dhaka",
    disable: true,
  },
  {
    dim: "3",
    id: "upozila",
    title: "Upozila",
    isMandatory: true,
    val: "Dhaka",
    disable: true,
  },
  {
    dim: "3",
    id: "postOffice",
    title: "Post Office",
    isMandatory: false,
    placeholder: "Enter Post Office",
    val: "Rampura",
    disable: true,
  },
  {
    dim: "3",
    id: "postalCode",
    title: "Postal Code",
    isMandatory: false,
    placeholder: "Enter Postal Code",
    val: "1219",
    disable: true,
  },
  {
    dim: "3",
    id: "additionalMouzaOrMoholla",
    title: "Mouza/Moholla",
    isMandatory: false,
    placeholder: "Enter Mouza/Moholla",
    val: "Moulovitek",
    disable: true,
  },
  {
    dim: "3",
    id: "additionalVillageOrRoad",
    title: "Village/Road",
    isMandatory: true,
    placeholder: "Enter Village/Road",
    val: "Sekhk Para, Road No 12",
    disable: true,
  },
  {
    dim: "3",
    id: "homeOrHoldingNo",
    title: "House/Holding No",
    isMandatory: true,
    placeholder: "Enter House/Holding No",
    val: "32",
    disable: true,
  },
];

export let ecData = {
  data: {
    status: "OK",
    statusCode: "SUCCESS",
    success: {
      data: {
        jobId: "31GMQE5X72CJJ",
        result: "MATCH FOUND",
        verificationResponse: {
          voterInfo: {
            name: "মঈন মুস্তাকিম",
            nameEn: "Moin Mostakim",
            bloodGroup: "B+",
            dateOfBirth: "1989-10-25",
            father: "মোঃ নাছির উদ্দিন",
            mother: "মনোয়ারা বেগম",
            spouse: "",
            nationalId: "123456789",
            occupation: "ছাত্র/ছাত্রী",
            permanentAddress: {
              division: "ঢাকা",
              district: "ঢাকা",
              rmo: "1",
              upozila: "ঢাকা",
              postOffice: "ঢাকা",
              postalCode: "",
              wardForUnionPorishod: 1,
              additionalMouzaOrMoholla: "",
              additionalVillageOrRoad: "ঢাকা",
              homeOrHoldingNo: "",
              region: "ঢাকা",
            },
            photo:
              "http://localhost:8989/file/Photo-ba02a2c4-a273-102b-b531-809d930a783c.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=fileobj%2F20210517%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210517T083535Z&X-Amz-Expires=120&X-Amz-SignedHeaders=host&X-Amz-Signature=f8698e3b8ed0e75ce29b058d1e88ccd0409f44fe3802176d72097c7453453135",
            presentAddress: {
              division: "ঢাকা",
              district: "ঢাকা",
              rmo: "9",
              upozila: "মোহাম্মদপুর",
              cityCorporationOrMunicipality: "ঢাকা উত্তর সিটি কর্পোরেশন",
              unionOrWard: "ওয়ার্ড নং-10",
              postOffice: "মোহাম্মদপুর",
              postalCode: "1207",
              wardForUnionPorishod: 0,
              additionalMouzaOrMoholla: "তাজমহল রোড",
              additionalVillageOrRoad: "",
              homeOrHoldingNo: "৫/১",
              region: "ঢাকা",
            },
          },
        },
      },
    },
  },
  result: {
    error: false,
    errorMsg: "",
    statusCode: 200,
  },
};
