export let listofFirst = [
  {
    dim: "6",
    id: "passportNumber",
    title: "Passport Number",
    isMandatory: true,
    placeholder: "Enter Passport Number",
    disable: false,
  },
  {
    dim: "6",
    id: "fullNameEn",
    title: "Full Name",
    isMandatory: true,
    placeholder: "Enter full Name",
    val: "Moin Mostakin",
    disable: false,
  },
  {
    dim: "6",
    id: "dob",
    title: "Date of birth",
    isMandatory: true,
    placeholder: "Enter date of birth",
    disable: false,
  },
  {
    dim: "6",
    id: "fullNameBn",
    title: "পূর্ণনাম",
    isMandatory: true,
    placeholder: "পূর্ণনাম",
    disable: false,
  },
  {
    dim: "6",
    id: "mobile",
    title: "Mobile Number",
    isMandatory: true,
    placeholder: "Mobile Number",
    val: "01921921987",
    disable: true,
  },
  {
    dim: "6",
    id: "email",
    title: "E-mail",
    isMandatory: false,
    placeholder: "Enter E-mail",
    val: "moin@commlinkinfotech.com",
    disable: false,
  },
];

export let listofSecond = [
  {
    dim: "4",
    id: "father",
    title: "Father",
    isMandatory: true,
    placeholder: "Enter Father's Name",
    disable: false,
  },
  {
    dim: "4",
    id: "mother",
    title: "Mother",
    isMandatory: true,
    placeholder: "Enter Mother's Name",
    disable: false,
  },
  {
    dim: "4",
    id: "spouse",
    title: "Spouse",
    isMandatory: false,
    placeholder: "Enter Spouse's Name",
    disable: false,
  },
  {
    dim: "4",
    id: "nationality",
    title: "Nationality",
    options: [
      { id: "bangladeshi", value: "bangladeshi", title: "Bangladeshi" },
      { id: "india", value: "ind", title: "India" },
    ],
    isMandatory: true,
    disable: false,
  },
  {
    dim: "4",
    id: "gender",
    title: "Gender",
    isMandatory: true,
    options: [
      { id: "male", value: "male", title: "Male" },
      { id: "female", value: "female", title: "Female" },
      { id: "others", value: "others", title: "Others" },
    ],
    disable: false,
  },
  {
    dim: "4",
    id: "maritalStatus",
    title: "Marital Status",
    isMandatory: false,
    options: [
      { id: "single", value: "single", title: "Single" },
      { id: "married", value: "married", title: "Married" },
    ],
    disable: false,
  },
];
export let listofThird = [
  {
    dim: "4",
    id: "country",
    title: "Country",
    isMandatory: true,
    options: [
      { id: "bd", value: "Bangladesh", title: "Bangladesh" },
      { id: "india", value: "India", title: "India" },
    ],
    disable: false,
  },
  {
    dim: "4",
    id: "division",
    title: "Division",
    isMandatory: false,
    placeholder: "Enter Division",
    disable: false,
  },
  {
    dim: "4",
    id: "district",
    title: "District",
    isMandatory: false,
    placeholder: "Enter District",
    disable: false,
  },
  {
    dim: "4",
    id: "upozila",
    title: "Upozila",
    isMandatory: false,
    placeholder: "Enter Upozila",
    disable: false,
  },
  {
    dim: "4",
    id: "cityCorporationOrMunicipality",
    title: "City/Municipality",
    isMandatory: false,
    placeholder: "Enter City/Municipality",
    disable: false,
  },
  {
    dim: "4",
    id: "unionOrWard",
    title: "Union/Ward",
    isMandatory: false,
    placeholder: "Enter Union or Ward",
    disable: false,
  },
  {
    dim: "4",
    id: "postOffice",
    title: "Post Office",
    isMandatory: false,
    placeholder: "Enter Post Office",
    disable: false,
  },
  {
    dim: "4",
    id: "postalCode",
    title: "Postal Code",
    isMandatory: false,
    placeholder: "Enter Postal Code",
    disable: false,
  },
  {
    dim: "4",
    id: "additionalMouzaOrMoholla",
    title: "Mouza/Moholla",
    isMandatory: false,
    placeholder: "Enter Mouza/Moholla",
    disable: false,
  },
  {
    dim: "4",
    id: "additionalVillageOrRoad",
    title: "Village/Road",
    isMandatory: false,
    placeholder: "Enter Village/Road",
    disable: false,
  },
  {
    dim: "4",
    id: "homeOrHoldingNo",
    title: "House/Holding No",
    isMandatory: false,
    placeholder: "Enter House/Holding No",
    disable: false,
  },
];
export let listofForth = [
  {
    dim: "4",
    id: "division",
    title: "Division",
    isMandatory: false,
    placeholder: "Enter Division",
    disable: false,
  },
  {
    dim: "4",
    id: "district",
    title: "District",
    isMandatory: false,
    placeholder: "Enter District",
    disable: false,
  },
  {
    dim: "4",
    id: "upozila",
    title: "Upozila",
    isMandatory: false,
    placeholder: "Enter Upozila",
    disable: false,
  },
  {
    dim: "4",
    id: "postOffice",
    title: "Post Office",
    isMandatory: false,
    placeholder: "Enter Post Office",
    disable: false,
  },
  {
    dim: "4",
    id: "postalCode",
    title: "Postal Code",
    isMandatory: false,
    placeholder: "Enter Postal Code",
    disable: false,
  },
  {
    dim: "4",
    id: "additionalMouzaOrMoholla",
    title: "Mouza/Moholla",
    isMandatory: false,
    placeholder: "Enter Mouza/Moholla",
    disable: false,
  },
  {
    dim: "4",
    id: "additionalVillageOrRoad",
    title: "Village/Road",
    isMandatory: false,
    placeholder: "Enter Village/Road",
    disable: false,
  },
  {
    dim: "4",
    id: "homeOrHoldingNo",
    title: "House/Holding No",
    isMandatory: false,
    placeholder: "Enter House/Holding No",
    disable: false,
  },
];
export function convertecDataToPI(data) {
  let convertedData = {
    identifierNumber: data.nationalId,
    fullNameBn: data.name,
    fullNameEn: data.nameEn,
    dob: data.dateOfBirth,
    father: data.father,
    mother: data.mother,
    spouse: data.spouse,
    mobile: data.mobileNumber,
    presentAddress: { ...data.presentAddress },
    permanentAddress: { ...data.permanentAddress },
  };
  return convertedData;
}
